server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: api-gateway-service

  cloud:
    routes:
      - id: member-service
        uri: lb:http://localhost:9001/
        predicates:
          - Path=/first-service/**
      - id: member-service
        uri: lb:http://localhost:9002/
        predicates:
          - Path=/second-service/**