spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ssgdb
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
        hibernate:
          format_sql: true

# JWT 관련 값을 주입시켜 생성시켜야 한다. 밖으로 노출되면 안된다.
JWT:
  SECRET_KEY: 6286783ee2dc2582300bd874944c3292ea903bfb93aa1e3f70a86fc40c042fc7
  EXPIRATION_TIME: 300000     # 한 시간
#  refresh-token-expiration: 86400000      # 일주일

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true